### ISSUE TITLE
The display does not show short numbers

### ISSUE THREAD

**Issue by old-rich** [Tinkertanker/pxt-alphanumeric-ht16k33#5]
Hello, there is an issue while showing short numbers (less than or equal 4 digits) on the display. It doesn't work, display is dark for those. If the number longer than 4 digits it works. For strings all mentioned above work well.

**Comment by DeXin64** [comment]
There was a problem displaying short numbers (less than or equal to 4 digits) on the display. How to use this question, I want to know about the use process

**Comment by old-rich** [comment]
Sorry for late anwer and appreciate if you coul dhelp to solve the issue.
The Alphanumeric display was tested with microbit connected throuch Sensor:bit extension module. Just needed to connect through I2C.
Here is an example that works well
https://makecode.microbit.org/_2f0FHvK3DRgi
And here is the one that doesnt work
https://makecode.microbit.org/_f7VCwE94jV1c
The problem is that it doesnt work for numbers shorter or wqual to 4 digits.

**Comment by DeXin64** [comment]
We are deeply grateful for bringing this issue to our attention as it plays a vital role in enhancing our product experience. We have meticulously documented the bug you reported and sincerely apologize for any inconvenience it may have caused.

Presently, our technical team has promptly engaged and is diligently working to identify the root cause of the issue and initiate the repair process. We assure you that we are striving for an efficient resolution to restore your seamless experience as soon as possible.

Should you have any further questions or require additional assistance during this period, please do not hesitate to reach out to us. Your patience and understanding are greatly appreciated as we work towards a swift resolution.

Once again, thank you for your valuable feedback, and we look forward to promptly rectifying this matter for you.

**Comment by old-rich** [comment]
Hello, after some time I would like to ask if you have found any solution to this problem. Please let me know.

**Comment by DeXin64** [comment]
Hello, you can send the specific issues to my email for processing. The email is: yang@elecfreaks.com.cn
